name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: linux
            runner: ubuntu-24.04-arm
            artifact_name: dealer-linux-arm64
          - os: linux
            runner: ubuntu-latest
            artifact_name: dealer-linux-amd64
          - os: macos
            runner: macos-latest
            artifact_name: dealer-macos-arm64
          - os: macos
            runner: macos-15-intel
            artifact_name: dealer-macos-amd64
          # It is tempting to add Windows here, too, but you'll run into
          # compilation errors because the code imports <netinet/in.h>, which is
          # a POSIX-only thing. The Windows folks can try using WSL to run the
          # Linux version instead.

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up build environment - Linux
        if: matrix.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc flex yacc make

      - name: Set up build environment - Mac
        if: matrix.os == 'macos'
        run: brew install gcc flex byacc make

      - name: Build the executable
        run: |
          make
          strip dealer
          zip ${{ matrix.artifact_name }} dealer

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.artifact_name }}.zip
          path: ${{ matrix.artifact_name }}.zip

  source:
    name: Package Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Package source code
        run: |
          pwd
          ls -lah
          cd ..
          ls -lah
          zip -r dealer-source-code dealer
          mv dealer-source-code.zip dealer

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: dealer-source-code.zip
          path: dealer-source-code.zip


  release:
    name: Create Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*/*
          draft: true
          prerelease: false
